### ISSUE TITLE
[테스트 데이터 생성기] CH 03. CLIP 03. 뷰 만들기: 자료형 선택 화면

### ISSUE THREAD

**Issue by ChanceMissed** [ChanceMissed/test-data#47]
이번 프로젝트에서 참고하고 있는 Mockaroo 를 보면, 각 필드 자료형을 클릭할 때 큰 팝업을 볼 수 있다.
이를 구현하는 것을 검토한다.

## Todo
* [ ] 관련 디자인 기술 조하사하기
* [x] 구현이 필요한 기능 정리
  * 자료형을 모두 보여준다.
  * 자료형을 그룹별로 보여준다.
  * 자료형은 검색 가능해야 한다.
* [x] 자료형 선택화면 구현 여부 의사결정
