### ISSUE TITLE
[테스트 데이터 생성기] CH 2. CLIP 05. 스프링 부트 프로젝트 초기화하기

### ISSUE THREAD

**Issue by ChanceMissed** [ChanceMissed/test-data#5]
한글 테스트 데이터 자동 생성기 서비스를 만들기 위한 소스코드 바탕을 준비한다.

## Todo
* [x] Spring Initializr: 자바 21 + 스프링 부트 3.3 으로 프로젝트 시작하기
* [x] 자바 21: 경고 로그 원인 찾고 제거하기
  * Class data sharing(CDS) 경고
  * Dynamic loading of agents 경고
* [x] 기초 application properties 셋업
* [x] 미리 해둘 필요가 있는 기초 설정 코드 작성해두기 
  * JPA
  * Security
